name: GitHub-Profile-3D-Contrib

on:
  schedule: # 월요일 03:00 JST == 일요일 18:00 UTC
    - cron: "0 18 * * 0"
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: generate-gitbub-profile-3d-contrib
    steps:
      - uses: actions/checkout@v3
      - uses: yoshi389111/github-profile-3d-contrib@0.7.1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          USERNAME: ${{ github.repository_owner }}
      - name: Commit & Push
        run: |
          git config --global user.name KimGwangJe
          git config --global user.email gwangjeg14@gmail.com
          git add -A
          git commit -m "generated"
          git push
